name: 'resource_type'
description: 'Expandir WADL y crear los paquetes Maven correspondientes'
inputs:
  path:
    description: 'resource_type WADL file path'
    required: true
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
