name: 'resource_type'
description: 'Expandir WADL y crear los paquetes Maven correspondientes'
inputs:
  changes:
    description: 'Cambios realizados en el commit que provoc贸 la ejecuci贸n de esta acci贸n'
    required: true
outputs:
  time:
    description: 'Momento en el que se ejecuta la acci贸n'
runs:
  using: 'node16'
  main: 'index.js'
