name: Java CI
on:
  push:
    paths:
    - '**.java'
    - '.github/workflows/build.yml'
    - 'pom.xml'
    - 'settings.xml'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
          server-id: output
      - run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGES }}
