name: Java CI
on:
  push:
    paths:
    - '**.java'
    - '.github/workflows/build.yml'
    - 'pom.xml'
    - 'settings.xml'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.READ_PACKAGES }}
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - run: |
          mvn --batch-mode package
          tree
          mkdir -p docs
          mv target/resource_type-1.0-SNAPSHOT.jar docs/build.jar
      - uses: EndBug/add-and-commit@v8
        with:
          add: docs/build.jar
          default_author: github_actions

